repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: check-end-of-file-fixer
    -   id: trailing-whitespace
