repos:
-   repo: local
    hooks:
    -   id: black
        name: run black formatter
        language: system
        entry: make black
    -   id: reorder-python-imports
        name: isort
        language: system
        entry: make isort
    -   id: autoflake
        name: autoflake - remove unused imports and unused variables
        language: system
        entry: make autoflake
    -   id: radon
        name: radon - cyclomatic complexity
        language: system
        entry: make radon
