[logging]
disable_existing_loggers = true
version = 1

[logging.formatters]

[logging.formatters.standard]
format = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

[logging.handlers]

[logging.handlers.default]
class = "logging.StreamHandler"
formatter = "standard"
level = "INFO"
stream = "ext://sys.stdout" # default is stderr

[logging.handlers.file_handler]
class = "logging.handlers.TimedRotatingFileHandler"
filename = "app.log"
formatter = "standard"
level = "INFO"
when = "m" # minute
interval = 1 # quantity of 'when'

[logging.loggers.''] # root logger
handlers = ["default", "file_handler"]
level = "INFO"
propogate = false
